### ISSUE TITLE
missing the most important scripts 

### ISSUE THREAD

**Issue by 0x1orz** [eyzhao/hrdetect-pipeline#1]
Thanks for your works .
when I read the file hrdetect-pipeline\Snakefile , I fond that the most important scripts /scripts/hrdetect/hrdetect_input_table.R and /scripts/hrdetect/compute_hrdetect.R were  missing.

Could you share these ?

**Comment by eyzhao** [comment]
Apologies for the oversight. These scripts are now part of the repo via commit 100c662652b815fb85d05eaed4b526708a306ce7

**Comment by 0x1orz** [comment]
Thanks. And I am studying your paper about this pipeline. But I have no access to the data, the supplementary files of the paper. Could you share these important files or the testing sets for this pipeline?
BTW, my email is iwuchu@126.com. THX ,again.

**Comment by eyzhao** [comment]
Yes, this was a known issue that Supplementary Information was not linked at the time of publication. Clinical Cancer Research has not corrected this issue, and you can find the PDF under the "Figures and Data" tab of the online version of the paper.

Here is a direct link to the supplementary information: http://clincancerres.aacrjournals.org/highwire/filestream/160228/field_highwire_adjunct_files/0/185837_2_supp_4280021_9wj959.pdf
