### ISSUE TITLE
Example input files

### ISSUE THREAD

**Issue by sigven** [eyzhao/hrdetect-pipeline#10]
Hi,

Thanks a lot for this contribution, the workflow is bound to be very useful in many settings. However, I believe it would be valuable to also provide a bundle/zip with example input files to see how the input looks for a successful run, and what it produces. I could not see this info anywhere? 

An additional question: Are all the input files (SNVs, deletions, CNAs with LOH info, SVs) strictly necessary to make a prediction/detection, or is the implementation able to assign a prediction based on a subset of the input data (e.g. SNVs, InDels, and CNAs without LOH info)?

regards,
Sigve

**Comment by SeanTomlinson30** [comment]
This indeed would be helpful!

**Comment by eyzhao** [comment]
Example data added in commit 32e609f0479780e2072bb4b0c39190660d7eb634
