### ISSUE TITLE
Could not read from remote repository

### ISSUE THREAD

**Issue by lianyh** [eyzhao/hrdetect-pipeline#8]
HRDetect
Herty Liany
eric@eyzhao.com
Dear Eric,
i tried to git clone the HRDetect from github repository:

https://github.com/eyzhao/hrdetect-pipeline.git

It is successful, however when i attempted to perform "make"  in order to build the source project, it failed with message:

_**Cloning into 'git/hrdtools'
Permission denied(publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
Makefile:30: recipe for target 'git/hrdtools' failed
make: *** [git/hrdtools] Error 128**_

![image](https://user-images.githubusercontent.com/23184681/41519656-0473b380-72fc-11e8-8aaa-b3cbb436001f.png)

I am running in linux environment.
thanks very much for your help.

Regards,
Herty

**Comment by BastienNguyen** [comment]
I had the same issue, try 
`git clone https://git@github.com/eyzhao/hrdtools.git` 
And each time this happens replace the git by https://

**Comment by lianyh** [comment]
It works now... thanks very much Nguyen :) :+1: 

Best,
Herty

**Comment by eyzhao** [comment]
Thanks @BastienNguyen 
@lianyh cloning by ssh requires a public key. Glad you are able to access the repo by https. Please feel free to flag any additional issues.

For more info: https://help.github.com/articles/which-remote-url-should-i-use/
